version: '3.9'
#networks:
# frontend:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.80.0.0/16
services:
## Nginx #########################################
    nginx:
      image: ${DOCKER_REGISTRY}/openresty:latest
      container_name: nginx
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - /etc/ngx-openresty/nginx.conf:/etc/nginx/nginx.conf
        - /etc/ngx-openresty/include/:/etc/nginx/include/
        - /etc/ngx-openresty/conf.d/:/etc/nginx/conf.d/
        - /etc/cert/:/etc/cert/
        - /var/log/nginx/:/var/log/nginx/
        - /opt/verynginx/configs/config.json:/opt/verynginx/configs/config.json
      #ports:
      #  - "${NGINX_HTTP_PORT}:80"
      #  - "${NGINX_HTTPS_PORT}:443"
      #  - "${NGINX_PORT_8080}:8080"
      #  - "${NGINX_PORT_8443}:8443"
      #  - "${NGINX_PORT_8880}:8880"
      environment:
        - TZ=Asia/Shanghai
        - TMP=1
      network_mode: "host"
      #networks:
      #  - frontend
      hostname: ${NGINX_HOSTNAME}
      mem_limit: 512M
      mem_reservation: 64M
      cpus: 1
      restart: always
